# Build AutoCorrode for PRs
name: Build AutoCorrode for PRs

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: makarius/isabelle:Isabelle2025
      options: --user root

    steps:
      - name: Checkout AutoCorrode
        uses: actions/checkout@v3
      
      - name: Setup Isabelle
        uses: ./.github/actions/setup-isabelle-action

      # Build with HTML documentation, to make sure we can deploy to pages on merge
      - name: Build AutoCorrode
        run: |
          $ISABELLE_HOME/bin/isabelle build -v -b -d . -o browser_info -d $AFP_COMPONENT_BASE/Word_Lib AutoCorrode
